name: myrex11
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated bflutter upgrade y dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  sdk: ">=2.16.1 <9.0.0"


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
#  connectivity: ^3.0.6
  shared_preferences: ^2.0.7
  http:
  fluttertoast: ^8.0.8
  image_picker: ^1.1.2
  # sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  url_launcher: ^6.0.0
  carousel_slider: 5.0.0
  dotted_border: ^2.0.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  super_tooltip: ^1.0.1
  retrofit: ^3.0.0
  dio: ^4.0.0
  built_value: ^8.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.0.1
  retrofit_generator: ^4.0.1
  otp_autofill: ^3.0.2
  intl: 0.18.1
  custom_timer: ^0.0.6
  #package_info: any
  #package_info_plus: any
#  share: ^2.0.4
  shimmer: ^2.0.0
  another_flushbar: ^1.10.24
#  device_apps: ^2.2.0
  google_sign_in: ^5.1.0
#  device_info: ^2.0.2
  permission_handler: ^8.1.6
  get: 4.7.2
  file_picker: ^5.3.2
  flutter_dash: ^1.0.0
  flutter_svg: 2.1.0
  # geolocator: any
  # geocoding: ^2.0.5
  percent_indicator: ^4.2.3
  socket_io_client: ^1.0.2
  responsive_framework: ^0.2.0
  webview_flutter: ^2.3.1
  flutter_downloader: ^1.10.0
  flutter_neumorphic: ^3.2.0
  need_resume:
  firebase_dynamic_links:
  app_installer: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  get_ip_address: ^0.0.5
  pin_code_fields:
  package_info_plus: ^4.2.0
  progress_indicator: ^0.2.2
  # firebase_auth: ^5.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  encrypt: ^5.0.1
  crypto: ^3.0.2
  flutter_inappwebview: ^5.7.2+3
  android_alarm_manager_plus: ^4.0.3
  web_socket_channel: ^2.4.0
  firebase_auth: ^4.16.0
  google_fonts: ^5.1.0
  geolocator: 9.0.2
  geocoding: ^3.0.0
  provider: ^6.1.2
  # audioplayers: ^5.2.1
#  sign_in_with_apple: ^4.2.0
  # sign_in_with_apple: 5.0.0
  marquee: ^2.2.3
  awesome_notifications: 0.7.7
  device_info_plus: ^10.1.2
  connectivity_plus: 2.1.0
  share_plus: ^10.0.0
  just_the_tooltip: ^0.0.12

#  flutter_zxing: 1.5.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  app_links: ^5.0.0
  qr_flutter: ^4.1.0
#  installed_apps: ^1.6.0





dependency_overrides:
  file_picker: any
  geolocator_android: 4.6.1
  flutter_plugin_android_lifecycle: 2.0.18



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your applicatxion, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifImage/
    - assets/sounds/tick.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
